HOST: http://staging.eversnapapp.com:8090/

--- Spoff API ---
---
Spoff is an application to prevent people in social events from focusing on their phones. 
---

--
User Resource
Users can be registered with this resource. You can also retrieve you information
--
Get the current authenticated users details. Need to have api key authentication.
GET /api/v1/user/
> Content-Type: application/json
{}
< 200
< Content-Type: application/json
{ 
	"id": 123,
	"email": "umutgultepe@yahoo.com",
	"key": "i12312i312sdcc",
	"yahoo_id": "20893r54y29",
	"username": "umutgultepe",
	"karma": "karma"
}
+++++
< 401
< Content-Type: application/json
{ 
	"error": "Not authenticated"
}


Login/SignUp with Yahoo. 
POST /api/v1/user/
> Content-Type: application/json
{
	"access_token": "sogfwouı43hriıo23h4re02o3hr",
	"secret_token": "i2hr08932",
	"device_id": "1AB23ORM",
	"registration_id": "afsdfswe213"
}
< 201
< Content-Type: application/json
{
	"id": 123,
	"email": "umutgultepe@yahoo.com",
	"key": "i12312i312sdcc",
	"yahoo_id": "20893r54y29",
	"username": "umutgultepe",
	"karma": "karma"
}


Use this resource when a user unlocks his phone 
GET /api/v1/user/unlocked
> Content-Type: application/json
{
}
< 201
< Content-Type: application/json
{
}
+++++
< 404 
{
    "error": "User is not part of a table"
}


-- Table Resources --
This resource allows you to create, join, leave and delete tables
POST /api/v1/table/
{ 
	"code": "123asfv0"
}
< 201
< Content-Type: application/json
{
	"id": 5245243,
	"code": "123asfv0",
	"creator_id": "12134",
	"members": [
		{
			"id": 214231,
			"username": umutgultepe
		}
		.
		.
	]
}
+++++
< 409
{
	"error": "Table code already exists." 
}


This resource is for joining a table using table id.
POST /api/v1/table/<table_code>/join/
{ 
}
< 201
{
	"id": 5245243,
	"code": "123asfv0",
	"creator_id": "12134",
	"members": [
		{
			"id": 214231,
			"username": umutgultepe
		}
		.
		.
	]
}
+++++
< 404
{
}


This resource is for retrieving the table details from table code
GET /api/v1/table/<table_code>/
{ 
}
< 201
{
	"id": 5245243,
	"code": "123asfv0",
	"creator_id": "12134",
	"members": [
		{
			"id": 214231,
			"username": umutgultepe
		}
		.
		.
	]
}
+++++
< 404
{
}


This resource is for leaving a table using table id.
POST /api/v1/table/<table_code>/leave/
{ 
}
< 201
{
	"id": 5245243,
	"code": "123asfv0",
	"creator_id": "12134",
	"members": [
		{
			"id": 214231,
			"username": umutgultepe
		}
		.
		.
	]
}
+++++
< 404
{
}


This is for deleting a table
DELETE /api/v1/table/<table_code>/
{ 
}
< 204
< Content-Type: application/json
{
}